version: '3.9'

services:
  redis:
    image: redis:7.2
    container_name: redis-secure
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "mvc-rookies-list"]
    restart: always