//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_todolist.Commons.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mvc_todolist.Commons.Resources.LabelsResource", typeof(LabelsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        internal static string ActionTitleColumn {
            get {
                return ResourceManager.GetString("ActionTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm người dùng.
        /// </summary>
        internal static string AddPerson {
            get {
                return ResourceManager.GetString("AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string AddressTitleColumn {
            get {
                return ResourceManager.GetString("AddressTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi.
        /// </summary>
        internal static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi.
        /// </summary>
        internal static string AgeTitleColumn {
            get {
                return ResourceManager.GetString("AgeTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh.
        /// </summary>
        internal static string BirthYearLabel {
            get {
                return ResourceManager.GetString("BirthYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string CloseTxt {
            get {
                return ResourceManager.GetString("CloseTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        internal static string CreateButtonTxt {
            get {
                return ResourceManager.GetString("CreateButtonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới người dùng thành công.
        /// </summary>
        internal static string CreatedPersonSuccessMessage {
            get {
                return ResourceManager.GetString("CreatedPersonSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm người dùng.
        /// </summary>
        internal static string CreateNewPersonTitle {
            get {
                return ResourceManager.GetString("CreateNewPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string DateOfBirthTitleColumn {
            get {
                return ResourceManager.GetString("DateOfBirthTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string DeleteButtonTxt {
            get {
                return ResourceManager.GetString("DeleteButtonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng {0} đã được xóa thành công.
        /// </summary>
        internal static string DeletedPersonSuccessMessage {
            get {
                return ResourceManager.GetString("DeletedPersonSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        internal static string DetailPersonTitle {
            get {
                return ResourceManager.GetString("DetailPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        internal static string EnglishLang {
            get {
                return ResourceManager.GetString("EnglishLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất dữ liệu.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        internal static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string FirstNameTitleColumn {
            get {
                return ResourceManager.GetString("FirstNameTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        internal static string FromPlaceHolder {
            get {
                return ResourceManager.GetString("FromPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string FullNameTitleColumn {
            get {
                return ResourceManager.GetString("FullNameTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string GenderTitleColumn {
            get {
                return ResourceManager.GetString("GenderTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tốt nghiệp.
        /// </summary>
        internal static string GraduatedTitleColumn {
            get {
                return ResourceManager.GetString("GraduatedTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string LastnameTitleColumn {
            get {
                return ResourceManager.GetString("LastnameTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string LoginNav {
            get {
                return ResourceManager.GetString("LoginNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người già nhất.
        /// </summary>
        internal static string OldestPerson {
            get {
                return ResourceManager.GetString("OldestPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string OtherGender {
            get {
                return ResourceManager.GetString("OtherGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string PasswordTitleColumn {
            get {
                return ResourceManager.GetString("PasswordTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người dùng.
        /// </summary>
        internal static string PersonList {
            get {
                return ResourceManager.GetString("PersonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí.
        /// </summary>
        internal static string RegisterNav {
            get {
                return ResourceManager.GetString("RegisterNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rookies.
        /// </summary>
        internal static string RookiesNav {
            get {
                return ResourceManager.GetString("RookiesNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm....
        /// </summary>
        internal static string SearchPlacehodler {
            get {
                return ResourceManager.GetString("SearchPlacehodler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tới.
        /// </summary>
        internal static string ToPlaceHolder {
            get {
                return ResourceManager.GetString("ToPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string UpdateButtonTxt {
            get {
                return ResourceManager.GetString("UpdateButtonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng.
        /// </summary>
        internal static string UpdatePersonTitle {
            get {
                return ResourceManager.GetString("UpdatePersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string UsernameTitleColumn {
            get {
                return ResourceManager.GetString("UsernameTitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string VietnameseLang {
            get {
                return ResourceManager.GetString("VietnameseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        internal static string ViewDetailAction {
            get {
                return ResourceManager.GetString("ViewDetailAction", resourceCulture);
            }
        }
    }
}
